/**
 * TWMS REST API
 * TWMS REST API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type BackendConstAllowedMaintenanceFileName = '^[a-zA-Z0-9_-]+\\.(?i)(odt|doc|docx|txt|pdf)$';

export const BackendConstAllowedMaintenanceFileName = {
    AZAZ09IOdtdocdocxtxtpdf: '^[a-zA-Z0-9_-]+\\.(?i)(odt|doc|docx|txt|pdf)$' as BackendConstAllowedMaintenanceFileName
};