/**
 * TWMS REST API
 * TWMS REST API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type BackendConstAllowedKeyName = '^[a-zA-Z0-9_-]+\\.(?i)([a-z]{1,5})$';

export const BackendConstAllowedKeyName = {
    AZAZ09IAZ15: '^[a-zA-Z0-9_-]+\\.(?i)([a-z]{1,5})$' as BackendConstAllowedKeyName
};