/**
 * TWMS REST API
 * TWMS REST API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type BackendConstHourMinute = '^(2[0-3]|[01][0-9]):([0-5][0-9])$';

export const BackendConstHourMinute = {
    _20301090509: '^(2[0-3]|[01][0-9]):([0-5][0-9])$' as BackendConstHourMinute
};