/**
 * TWMS REST API
 * TWMS REST API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type BackendConstOnlyNumber = '^[0-9]+$';

export const BackendConstOnlyNumber = {
    _09: '^[0-9]+$' as BackendConstOnlyNumber
};