/**
 * TWMS REST API
 * TWMS REST API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SntpConfiguration } from './sntpConfiguration';

/**
 * Controller configuration parameters, e.g. hostname, domainname etc.
 */
export interface ControllerConfiguration { 
    hostName?: string;
    domainName?: string;
    dnsServer?: string;
    /**
     * Get set together with FirstDnsServer  Conversion
     */
    alternativeDnsServer?: string;
    /**
     * (sec.max. 255)
     */
    ipFragmentTtl?: number;
    sntpConfiguration?: SntpConfiguration;
    sftpPathProjectFile?: string;
    sftpPathProtocol?: string;
}