/**
 * TWMS REST API
 * TWMS REST API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type ControllerTypeEnum = 'Master' | 'DTE' | 'Slave' | 'Unknown';

export const ControllerTypeEnum = {
    Master: 'Master' as ControllerTypeEnum,
    DTE: 'DTE' as ControllerTypeEnum,
    Slave: 'Slave' as ControllerTypeEnum,
    Unknown: 'Unknown' as ControllerTypeEnum
};