/**
 * TWMS REST API
 * TWMS REST API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * DependOnStagnationFlushPlan with next flush times
 */
export interface DependOnStagnationFlushPlanDto { 
    /**
     * Timestamps for the next flush (pwc and pwh)
     */
    nextCheckTimes?: { [key: string]: string; };
    /**
     * Flush if this threshold is reached aka stagnation time max
     */
    intervalHours: number;
}