/**
 * TWMS REST API
 * TWMS REST API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DeviceUpdateFailedStatus } from './deviceUpdateFailedStatus';
import { DeviceUpdateGeneralStatus } from './deviceUpdateGeneralStatus';
import { DeviceUpdateRunningStatus } from './deviceUpdateRunningStatus';

export interface DeviceUpdateStatusInternal { 
    deviceUpdateGeneralStatus?: DeviceUpdateGeneralStatus;
    deviceUpdateRunningStatus?: DeviceUpdateRunningStatus;
    deviceUpdateFailedStatus?: DeviceUpdateFailedStatus;
    lastEmicoDeviceUpdateFailedStatus?: DeviceUpdateFailedStatus;
}