/**
 * TWMS REST API
 * TWMS REST API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CreatePortInput } from './createPortInput';

/**
 * data transfer object for creating a new device in frontend representation
 */
export interface DeviceCreateWithAncestorInput { 
    /**
     * Device name
     */
    name: string;
    /**
     * SerialNumber of Device
     */
    serialNumber: number;
    /**
     * Vendor ID of Device
     */
    vendorID: number;
    /**
     * Product Code of Device
     */
    productCode: number;
    /**
     * Revision Number of Device
     */
    revisionNumber: number;
    /**
     * Device Type Name
     */
    deviceTypeName: string;
    /**
     * Remark of Device
     */
    remark: string;
    /**
     * Maintenance Interval of Device
     */
    maintenanceInterval: string;
    /**
     * AncestorDevice_UUID
     */
    ancestorDevice_UUID: string;
    /**
     * AncestorDevice_Ports
     */
    ancestorDevice_Ports: Array<CreatePortInput>;
    /**
     * Last Maintenance Timestamp of Device
     */
    lastMaintenanceTimestamp: string;
    /**
     * CreatedBy User UUID
     */
    createdByUUID?: string;
    /**
     * Devices Variant stored to Preferences
     */
    deviceVariant?: string;
}