/**
 * TWMS REST API
 * TWMS REST API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * data transfer object for creating a new device in frontend representation
 */
export interface DeviceCreateInput { 
    /**
     * Device name
     */
    name: string;
    /**
     * SerialNumber of Device
     */
    serialNumber: number;
    /**
     * Revision Number of Device
     */
    revisionNumber: number;
    /**
     * Device Type Name
     */
    deviceTypeName: string;
    /**
     * Remark of Device
     */
    remark: string;
    /**
     * Maintenance Interval of Device
     */
    maintenanceInterval: number;
    /**
     * Last Maintenance Timestamp of Device
     */
    lastMaintenanceTimestamp: string;
    /**
     * Pre selected node id of the device
     */
    preSelectedNodeId?: number;
    /**
     * CreatedBy User UUID
     */
    createdByUUID?: string;
}