/**
 * TWMS REST API
 * TWMS REST API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type DeviceUpdateRunningStatus = 'FileCopy' | 'ExtractFile' | 'VerifySignature' | 'UpdateRunningOnDevice';

export const DeviceUpdateRunningStatus = {
    FileCopy: 'FileCopy' as DeviceUpdateRunningStatus,
    ExtractFile: 'ExtractFile' as DeviceUpdateRunningStatus,
    VerifySignature: 'VerifySignature' as DeviceUpdateRunningStatus,
    UpdateRunningOnDevice: 'UpdateRunningOnDevice' as DeviceUpdateRunningStatus
};