/**
 * TWMS REST API
 * TWMS REST API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface DTE { 
    /**
     * Device UUID
     */
    uuid: string;
    /**
     * Sekundärseite PWH (Ist)
     */
    secondaryActualPWH?: number;
    /**
     * Sekundärseite PWH (Soll)
     */
    secondaryTargetPWH?: number;
    /**
     * Sekundärseite Mischtemp. PWH + PWH-C (ist)
     */
    secondaryActualTemperaturePWHPWHC?: number;
    /**
     * Sekundärseite Temperatur PWH-C (ist)
     */
    secondaryActualTemperaturePWHC?: number;
    /**
     * Sekundärseite Volumenstrom PWH + PWH-C (Ist)
     */
    secondaryActualVolumeRatePWHPWHC?: number;
    /**
     * Primärseite Temperatur VL (Ist)
     */
    primaryTemperatureVL?: number;
    /**
     * Primärseite Pumpe Oben (Leistung)
     */
    primaryUpperPumpPower?: number;
    /**
     * Primärseite Pumpe Unten (Leistung)
     */
    primaryLowerPumpPower?: number;
    /**
     * Zirkulationspumpe (An/Aus)
     */
    isActiveCircPump?: number;
    /**
     * Zirkulationspumpe (An/Aus)
     */
    isActiveRegulation?: number;
    /**
     * Soll Temperatur PWH
     */
    actualPWHTemperature?: number;
    /**
     * Zirkulationspumpe angeschlossen
     */
    isCircPumpConnected?: number;
    /**
     * Zirkulationspumpe An/Aus
     */
    circPumpMode?: number;
    /**
     * DTE Variante
     */
    dteVariant?: number;
    /**
     * UFC angeschlossen
     */
    isUfcConnected?: number;
    /**
     * Werkseinstellungen wieder herstellen
     */
    factoryReset?: number;
    /**
     * Umschaltung Normabetrieb / Thermischer Desinfektionsmodus
     */
    switchNormalModeDisinfectionMode?: number;
    /**
     * Umschaltung Normalbetrieb / Grundbetrieb
     */
    switchNormalModeBasicMode?: number;
    /**
     * Funktionstest: Regelung PWH an/aus
     */
    functionTestControlPWHOnOffOne?: number;
    /**
     * Funktionstest: Regelung PWH an/aus
     */
    functionTestControlPWHOnOffTwo?: number;
    /**
     * Funktionstest: Pumpe oben ansteuern
     */
    functionTestUpperPumpTrigger?: number;
    /**
     * Funktionstest: Pumpe unten ansteuern
     */
    functionTestLowerPumpTrigger?: number;
}