/**
 * TWMS REST API
 * TWMS REST API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Type of an TwmsBackend.Services.DteFunctionTestService.DisplayElement.
 */
export type EDisplayElementType = 'IButton' | 'INumeric' | 'IString' | 'OInfo' | 'OValue';

export const EDisplayElementType = {
    IButton: 'IButton' as EDisplayElementType,
    INumeric: 'INumeric' as EDisplayElementType,
    IString: 'IString' as EDisplayElementType,
    OInfo: 'OInfo' as EDisplayElementType,
    OValue: 'OValue' as EDisplayElementType
};