/**
 * TWMS REST API
 * TWMS REST API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Configuration parameters for one ethernet interface
 */
export interface EthernetConfigurationInput { 
    enableInterface?: boolean;
    enableAutonegotiation?: boolean;
    macAddressFilter?: string;
    fastAging?: string;
    ethernetMtu?: number;
    /**
     * Could be IP v4 or v6
     */
    ipAddress?: string;
    /**
     * Get set together with the IpAddress  Conversion
     */
    prefixLength?: number;
    gateway?: string;
}