/**
 * TWMS REST API
 * TWMS REST API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type GpioPin = 'DIO0' | 'DIO1' | 'DIO2' | 'DIO3' | 'DIO4' | 'DIO5' | 'DIO6';

export const GpioPin = {
    DIO0: 'DIO0' as GpioPin,
    DIO1: 'DIO1' as GpioPin,
    DIO2: 'DIO2' as GpioPin,
    DIO3: 'DIO3' as GpioPin,
    DIO4: 'DIO4' as GpioPin,
    DIO5: 'DIO5' as GpioPin,
    DIO6: 'DIO6' as GpioPin
};