import { marker as _ } from '@biesbjerg/ngx-translate-extract-marker';

/**
 * TWMS REST API
 * TWMS REST API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type HygieneCleansingFailedDeviceReason = 'API.MESSAGE_TYPES.HygieneCleansingFailedDeviceReason.FailedTemperature' | 'API.MESSAGE_TYPES.HygieneCleansingFailedDeviceReason.Timeout' | 'API.MESSAGE_TYPES.HygieneCleansingFailedDeviceReason.FailedStart' | 'API.MESSAGE_TYPES.HygieneCleansingFailedDeviceReason.InitialDeviceStateIsNotOk' | 'API.MESSAGE_TYPES.HygieneCleansingFailedDeviceReason.DeviceStateAfterStartIsNotOk' | 'API.MESSAGE_TYPES.HygieneCleansingFailedDeviceReason.UnkownError';

export const HygieneCleansingFailedDeviceReason = {
    FailedTemperature: _('API.MESSAGE_TYPES.HygieneCleansingFailedDeviceReason.FailedTemperature') as HygieneCleansingFailedDeviceReason,
    Timeout: _('API.MESSAGE_TYPES.HygieneCleansingFailedDeviceReason.Timeout') as HygieneCleansingFailedDeviceReason,
    FailedStart: _('API.MESSAGE_TYPES.HygieneCleansingFailedDeviceReason.FailedStart') as HygieneCleansingFailedDeviceReason,
    InitialDeviceStateIsNotOk: _('API.MESSAGE_TYPES.HygieneCleansingFailedDeviceReason.InitialDeviceStateIsNotOk') as HygieneCleansingFailedDeviceReason,
    DeviceStateAfterStartIsNotOk: _('API.MESSAGE_TYPES.HygieneCleansingFailedDeviceReason.DeviceStateAfterStartIsNotOk') as HygieneCleansingFailedDeviceReason,
    UnkownError: _('API.MESSAGE_TYPES.HygieneCleansingFailedDeviceReason.UnkownError') as HygieneCleansingFailedDeviceReason
};