/**
 * TWMS REST API
 * TWMS REST API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CreatePortInput } from './createPortInput';

export interface LinkDevicePortToSensorInput { 
    /**
     * UUID of Ancestor Device the sensor should be linked to
     */
    deviceUUID: string;
    /**
     * UUID of th DevicePoint of the sensor
     */
    sensorPointUUID: string;
    /**
     * AncestorDevice_Ports
     */
    ancestorDevice_Ports: Array<CreatePortInput>;
    /**
     * reload Config (defaut: true)
     */
    reloadConfig?: boolean;
}