/**
 * TWMS REST API
 * TWMS REST API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * data transfer object for editing a message in frontend representation
 */
export interface MessageEditInput { 
    /**
     * new description of message
     */
    description: string;
    /**
     * new summary of message
     */
    summary: string;
}