/**
 * TWMS REST API
 * TWMS REST API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface NetworkInterfaceInfo { 
    name?: string;
    isUp?: boolean;
    isLoopbak?: boolean;
    macAddress?: string;
    ipAddressV4?: Array<string>;
    subnetmaskV4?: Array<string>;
    ipAddressV6?: Array<string>;
    prefixLengthV6?: Array<string>;
    mtuIpV4?: number;
    mtuIpV6?: number;
    gatewayAddresses?: Array<string>;
    dhcpAddresses?: Array<string>;
    dnsSuffix?: string;
    dnsAddresses?: Array<string>;
}