/**
 * TWMS REST API
 * TWMS REST API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type OutputDataType = 'JsonString' | 'CsvString' | 'CsvFile' | 'PdfFile';

export const OutputDataType = {
    JsonString: 'JsonString' as OutputDataType,
    CsvString: 'CsvString' as OutputDataType,
    CsvFile: 'CsvFile' as OutputDataType,
    PdfFile: 'PdfFile' as OutputDataType
};