/**
 * TWMS REST API
 * TWMS REST API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type PortTypeName = 'MultiIO' | 'GPIO_DigitalIn' | 'GPIO_DigitalOut' | 'TLC';

export const PortTypeName = {
    MultiIO: 'MultiIO' as PortTypeName,
    GPIODigitalIn: 'GPIO_DigitalIn' as PortTypeName,
    GPIODigitalOut: 'GPIO_DigitalOut' as PortTypeName,
    TLC: 'TLC' as PortTypeName
};