/**
 * TWMS REST API
 * TWMS REST API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * file info object (for output purposes)
 */
export interface ReportFileParametersDto { 
    /**
     * uuid of the user
     */
    userUuid?: string;
    /**
     * file name with extension
     */
    fileName?: string;
    /**
     * size of the file in bytes
     */
    sizeInBytes?: number;
}