/**
 * TWMS REST API
 * TWMS REST API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * data transfer object for updating a device in frontend representation
 */
export interface SetDeviceMainMetadataInput { 
    /**
     * Device UUID
     */
    uuid: string;
    /**
     * Device name
     */
    newName: string;
    /**
     * SerialNumber of Device
     */
    newSerialNumber: number;
    /**
     * Revision Number of Device
     */
    newRevisionNumber: number;
    /**
     * Device Type Name
     */
    newDeviceTypeName: string;
    /**
     * Remark of Device
     */
    newRemark: string;
}