/**
 * TWMS REST API
 * TWMS REST API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Configuration for sntp-client
 */
export interface SntpConfiguration { 
    /**
     * (S)NTP-Server Host Name Or IP Address
     */
    serverHostName?: string;
    /**
     * „Simple Network Time Protocol“ aktivieren
     */
    enable?: boolean;
    /**
     * (sec.max. 65535)
     */
    updateTime?: string;
    port123Enabled?: boolean;
}