/**
 * TWMS REST API
 * TWMS REST API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DisplayElement } from './displayElement';
import { ETestCaseStatus } from './eTestCaseStatus';
import { Localized } from './localized';

/**
 * Base class for the test cases.
 */
export interface TestCase { 
    name?: string;
    title?: Localized;
    testId?: string;
    readonly testerName?: string;
    deviceUuid?: string;
    testCaseIndex?: number;
    testCount?: number;
    readonly canRestart?: boolean;
    readonly canSkip?: boolean;
    readonly canCancel?: boolean;
    status?: ETestCaseStatus;
    readonly displayElements?: Array<Array<DisplayElement>>;
}