/**
 * TWMS REST API
 * TWMS REST API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ETestCaseStatus } from './eTestCaseStatus';
import { Localized } from './localized';

/**
 * Represents the result of a test case.
 */
export interface TestCaseResult { 
    testCaseName?: string;
    testCaseTitle?: Localized;
    testCaseResultStatus?: ETestCaseStatus;
    numTrials?: number;
    skipReason?: string;
    resultMessages?: Array<Localized>;
    readonly isSkipped?: boolean;
}