import { marker as _ } from '@biesbjerg/ngx-translate-extract-marker';

/**
 * TWMS REST API
 * TWMS REST API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type ThermalDisinfectionResetDeviceFailedReason = 'API.MESSAGE_TYPES.ThermalDisinfectionResetDeviceFailedReason.Exception';

export const ThermalDisinfectionResetDeviceFailedReason = {
    Exception: _('API.MESSAGE_TYPES.ThermalDisinfectionResetDeviceFailedReason.Exception') as ThermalDisinfectionResetDeviceFailedReason
};