import { marker as _ } from '@biesbjerg/ngx-translate-extract-marker';

/**
 * TWMS REST API
 * TWMS REST API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type ThermalDisinfectionFailedReason = 'API.MESSAGE_TYPES.ThermalDisinfectionFailedReason.SomeDevicesFailed' | 'API.MESSAGE_TYPES.ThermalDisinfectionFailedReason.Exception';

export const ThermalDisinfectionFailedReason = {
    SomeDevicesFailed: _('API.MESSAGE_TYPES.ThermalDisinfectionFailedReason.SomeDevicesFailed') as ThermalDisinfectionFailedReason,
    Exception: _('API.MESSAGE_TYPES.ThermalDisinfectionFailedReason.Exception') as ThermalDisinfectionFailedReason
};