/**
 * TWMS REST API
 * TWMS REST API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Defines a range of hours for a day, e.g. from 22:00 to 6:00
 */
export interface TimeRange { 
    /**
     * Start of the range, only hours and minutes are used, e.g. 02:03
     */
    fromHourMinute: string;
    /**
     * End of the range, only hours and minutes are used, e.g. 06:59
     */
    toHourMinute: string;
}