/**
 * TWMS REST API
 * TWMS REST API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface UnlinkDevicePortByUUIDInput { 
    /**
     * UUID of Ancestor Device the sensor should be linked to
     */
    deviceUUID: string;
    /**
     * reload Config (defaut: true)
     */
    reloadConfig?: boolean;
}