/**
 * TWMS REST API
 * TWMS REST API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * list of starting points for each weekday
 */
export interface WeekDays { 
    mon: Array<string>;
    tue: Array<string>;
    wed: Array<string>;
    thu: Array<string>;
    fri: Array<string>;
    sat: Array<string>;
    sun: Array<string>;
}