/**
 * TWMS REST API
 * TWMS REST API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface WireSenstT { 
    /**
     * Device UUID
     */
    uuid: string;
    /**
     * Temperatur
     */
    temperature?: number;
    /**
     * Temperatur Grenzwert min
     */
    temperatureLimitMin?: number;
    /**
     * Temperatur Grenzwert max
     */
    temperatureLimitMax?: number;
    /**
     * Zeit Grenzwertüberschreitung
     */
    timeLimitViolation?: number;
}