/**
 * TWMS REST API
 * TWMS REST API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface WireSensP { 
    /**
     * Device UUID
     */
    uuid: string;
    /**
     * Zeit Grenzwertüberschreitung
     */
    timeLimitViolation?: number;
    /**
     * Druckwert
     */
    pressureValue?: number;
    /**
     * Druck Grenzwert min
     */
    pressureValueLimitMin?: number;
    /**
     * Druck Grenzwert max
     */
    pressureValueLimitMax?: number;
}