export * from './activation.service';
import { ActivationService } from './activation.service';
export * from './controller.service';
import { ControllerService } from './controller.service';
export * from './controllerPoint.service';
import { ControllerPointService } from './controllerPoint.service';
export * from './devicePoint.service';
import { DevicePointService } from './devicePoint.service';
export * from './deviceUpdate.service';
import { DeviceUpdateService } from './deviceUpdate.service';
export * from './devices.service';
import { DevicesService } from './devices.service';
export * from './dteFunctionTest.service';
import { DteFunctionTestService } from './dteFunctionTest.service';
export * from './flush.service';
import { FlushService } from './flush.service';
export * from './functionTest.service';
import { FunctionTestService } from './functionTest.service';
export * from './image.service';
import { ImageService } from './image.service';
export * from './itemReports.service';
import { ItemReportsService } from './itemReports.service';
export * from './itemReportsFilter.service';
import { ItemReportsFilterService } from './itemReportsFilter.service';
export * from './itemReportsService.service';
import { ItemReportsServiceService } from './itemReportsService.service';
export * from './management.service';
import { ManagementService } from './management.service';
export * from './messages.service';
import { MessagesService } from './messages.service';
export * from './parameter.service';
import { ParameterService } from './parameter.service';
export * from './pointAddress.service';
import { PointAddressService } from './pointAddress.service';
export * from './projects.service';
import { ProjectsService } from './projects.service';
export * from './sessions.service';
import { SessionsService } from './sessions.service';
export * from './system.service';
import { SystemService } from './system.service';
export * from './update.service';
import { UpdateService } from './update.service';
export * from './users.service';
import { UsersService } from './users.service';
export * from './values.service';
import { ValuesService } from './values.service';
export const APIS = [ActivationService, ControllerService, ControllerPointService, DevicePointService, DeviceUpdateService, DevicesService, DteFunctionTestService, FlushService, FunctionTestService, ImageService, ItemReportsService, ItemReportsFilterService, ItemReportsServiceService, ManagementService, MessagesService, ParameterService, PointAddressService, ProjectsService, SessionsService, SystemService, UpdateService, UsersService, ValuesService];
